=== tuanflute275/BTL_XML/btl.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="id" type="xs:positiveInteger"></xs:element>

    <xs:element name="name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="3"></xs:minLength>
                <xs:maxLength value="50"></xs:maxLength>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="category_id">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"></xs:minInclusive>
                <xs:maxInclusive value="9"></xs:maxInclusive>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
    
     <xs:element name="desscription">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[\w ]+"></xs:pattern>
                <xs:maxLength value="128"></xs:maxLength>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
     <xs:element name="amount">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"></xs:minInclusive>
                <xs:maxInclusive value="9999"></xs:maxInclusive>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
     <xs:element name="price">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="100"></xs:minInclusive>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
     <xs:element name="size">
     	<xs:simpleType>
     		<xs:restriction base="xs:string">
     			<xs:enumeration value="M"></xs:enumeration>
     			<xs:enumeration value="L"></xs:enumeration>
     			<xs:enumeration value="XL"></xs:enumeration>
     			<xs:enumeration value="XXL"></xs:enumeration>
     		</xs:restriction>
     	</xs:simpleType>
     </xs:element>
    
     <xs:element name="image">
       <xs:complexType>
       	<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
       	<xs:attribute name="src" type="xs:string" use="optional"></xs:attribute>
       </xs:complexType>
    </xs:element>
    

    <xs:element name="Sanpham">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id"></xs:element>
                <xs:element ref="name"></xs:element>
                <xs:element ref="category_id"></xs:element>
                <xs:element ref="desscription"></xs:element>
                <xs:element ref="amount"></xs:element>
                <xs:element ref="price"></xs:element>
                <xs:element ref="size"></xs:element>
                <xs:element ref="image"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="DSSanpham">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Sanpham" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
         <xs:unique name="uniqueId">
            <xs:selector xpath="Sanpham/id"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:unique>
    </xs:element>

</xs:schema>

=== tuanflute275/BTL_XML/btl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-stylesheet href="yc1.xsl" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="yc2.xsl" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="yc3.xsl" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="yc4.xsl" type="text/xsl"?> -->
<?xml-stylesheet href="yc5.xsl" type="text/xsl"?>


<DSSanpham xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="btl.xsd">

  <Sanpham>
    <id>1</id>
    <name>Áo sơ mi</name>
    <category_id>1</category_id>
    <desscription>Sơ mi cao cấp</desscription>
    <amount>100</amount>
    <price>1000000</price>
    <size>M</size>
    <image type="jpg" src="a.jpg"/>
  </Sanpham>
  
  <Sanpham>
  	<id>2</id>
  	<name>Quần bò</name>
  	<category_id>2</category_id>
  	<desscription>Quần bò rách</desscription>
  	<amount>200</amount>
  	<price>200000</price>
  	<size>L</size>
  	<image type="png" src="Anh.png"/>
  </Sanpham>
  
  <Sanpham>
  	<id>3</id>
  	<name>Quần âu</name>
  	<category_id>3</category_id>
  	<desscription>Quần Âu</desscription>
  	<amount>9999</amount>
  	<price>1000000</price>
  	<size>XL</size>
  	<image type="jpg" src="1.jpg"/>
  </Sanpham>
  
    <Sanpham>
  	<id>4</id>
  	<name>Quần ngố</name>
  	<category_id>4</category_id>
  	<desscription>Ngố tàu</desscription>
  	<amount>1</amount>
  	<price>100000000</price>
  	<size>XXL</size>
  	<image type="jpg" src="Pro.jpg"/>
  </Sanpham>
  
</DSSanpham>
